load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "abort_debounce",
    srcs = glob(["src/**/*.rs"]),
    edition = "2024",
)

rust_test(
    name = "tests",
    crate = ":abort_debounce",
    edition = "2024",
    deps = ["@crates//:rstest"],
)
